<a href="https://colab.research.google.com/github/harshit7271/Deep_learning_with_PyTorch/blob/main/Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource Notebook : (https://www.learnpytorch.io/00_pytorch_fundamentals/)

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.8.0+cu126


In [3]:
# Tensors

## Creating tensors
Pytorch tensors are craeted using `torch.tensor()` = (https://pytorch.org/docs/stable/tensors.html)

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as Python int

scalar.item()

7

In [7]:
# vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR = torch.tensor([[[[1,2,3,4],
                        [3,6,9,12],
                        [2,4,6,8],
                        [7,3,4,5]]]])
TENSOR


tensor([[[[ 1,  2,  3,  4],
          [ 3,  6,  9, 12],
          [ 2,  4,  6,  8],
          [ 7,  3,  4,  5]]]])

In [16]:
TENSOR.ndim

4

In [17]:
TENSOR.shape

torch.Size([1, 1, 4, 4])

In [18]:
TENSOR[0]

tensor([[[ 1,  2,  3,  4],
         [ 3,  6,  9, 12],
         [ 2,  4,  6,  8],
         [ 7,  3,  4,  5]]])

### Random Tensors

It is imp bcz the way many nueral networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better representation of the data

`Strat with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [19]:
# creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0454, 0.2221, 0.2622, 0.2859],
        [0.7452, 0.2206, 0.9662, 0.1835],
        [0.8632, 0.8201, 0.0062, 0.8452]])

In [20]:
random_tensor.ndim

2

In [21]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [22]:
# create a tensor of all zeroes

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [26]:
# Useage of torch.arange()

one_to_six = torch.arange(start =0, end =21, step = 2)
one_to_six

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
# creating tensor like

six_zeros= torch.zeros_like(input = one_to_six)
six_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Tensor Datatypes**
**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning
   1. Tensor not right datatype
   2. Tensor not right shape
   3. Tensor not on the right device

In [28]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor(eg - float32 or float16)
                               device = None, # What device your tensor on
                               requires_grad = False) # Whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting Information from Tensors (tensor attributes) :
   1. Tensor not right datatype - to do get datatype from a tensor, use `tensor.dtype`
  2. Tensor not right shape -  to get shape from a tensor, use `tensor.shape` or  `tensor.size()`
   3. Tensor not on the right device - to get device from a tensor, use `tensor,device`

In [42]:
# Create a tensor

dummy_tensor = torch.rand(3,4)
dummy_tensor = dummy_tensor.type(torch.float16)    # we can change its datatype as we want to, this just to showcase
dummy_tensor

tensor([[0.4163, 0.7788, 0.7930, 0.7988],
        [0.5703, 0.5654, 0.2458, 0.5542],
        [0.0264, 0.4373, 0.0547, 0.8677]], dtype=torch.float16)

In [43]:
# Find out details about dummy tensor

print(dummy_tensor)

print(f"Datatype of tensor : {dummy_tensor.dtype}")
print(f"Shape of tensor : {dummy_tensor.shape}")
print(f"Deivce of tensor : {dummy_tensor.device}")

tensor([[0.4163, 0.7788, 0.7930, 0.7988],
        [0.5703, 0.5654, 0.2458, 0.5542],
        [0.0264, 0.4373, 0.0547, 0.8677]], dtype=torch.float16)
Datatype of tensor : torch.float16
Shape of tensor : torch.Size([3, 4])
Deivce of tensor : cpu
