<a href="https://colab.research.google.com/github/harshit7271/Deep_learning_with_PyTorch/blob/main/Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource Notebook : (https://www.learnpytorch.io/00_pytorch_fundamentals/)

In [126]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.8.0+cu126


In [127]:
# Tensors

## Creating tensors
Pytorch tensors are craeted using `torch.tensor()` = (https://pytorch.org/docs/stable/tensors.html)

In [128]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [129]:
scalar.ndim

0

In [130]:
# get tensor back as Python int

scalar.item()

7

In [131]:
# vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [132]:
vector.ndim

1

In [133]:
vector.shape

torch.Size([2])

In [134]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [135]:
MATRIX.ndim

2

In [136]:
MATRIX[0]

tensor([7, 8])

In [137]:
MATRIX[1]

tensor([ 9, 10])

In [138]:
MATRIX.shape

torch.Size([2, 2])

In [139]:
# TENSOR
TENSOR = torch.tensor([[[[1,2,3,4],
                        [3,6,9,12],
                        [2,4,6,8],
                        [7,3,4,5]]]])
TENSOR


tensor([[[[ 1,  2,  3,  4],
          [ 3,  6,  9, 12],
          [ 2,  4,  6,  8],
          [ 7,  3,  4,  5]]]])

In [140]:
TENSOR.ndim

4

In [141]:
TENSOR.shape

torch.Size([1, 1, 4, 4])

In [142]:
TENSOR[0]

tensor([[[ 1,  2,  3,  4],
         [ 3,  6,  9, 12],
         [ 2,  4,  6,  8],
         [ 7,  3,  4,  5]]])

### Random Tensors

It is imp bcz the way many nueral networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better representation of the data

`Strat with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [143]:
# creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0686, 0.2903, 0.4742, 0.3363],
        [0.6784, 0.7398, 0.9657, 0.3483],
        [0.3073, 0.8219, 0.5585, 0.0483]])

In [144]:
random_tensor.ndim

2

In [145]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [146]:
# create a tensor of all zeroes

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [147]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [148]:
# create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [149]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [150]:
# Useage of torch.arange()

one_to_six = torch.arange(start =0, end =21, step = 2)
one_to_six

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [151]:
# creating tensor like

six_zeros= torch.zeros_like(input = one_to_six)
six_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Tensor Datatypes**
**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning
   1. Tensor not right datatype
   2. Tensor not right shape
   3. Tensor not on the right device

In [152]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor(eg - float32 or float16)
                               device = None, # What device your tensor on
                               requires_grad = False) # Whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [153]:
float_32_tensor.dtype

torch.float32

In [154]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [155]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [156]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [157]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting Information from Tensors (tensor attributes) :
   1. Tensor not right datatype - to do get datatype from a tensor, use `tensor.dtype`
  2. Tensor not right shape -  to get shape from a tensor, use `tensor.shape` or  `tensor.size()`
   3. Tensor not on the right device - to get device from a tensor, use `tensor,device`

In [158]:
# Create a tensor

dummy_tensor = torch.rand(3,4)
dummy_tensor = dummy_tensor.type(torch.float64)    # we can change its datatype as we want to, this just to showcase
dummy_tensor

tensor([[0.6465, 0.4172, 0.6101, 0.6392],
        [0.8202, 0.7495, 0.5904, 0.0202],
        [0.6045, 0.7881, 0.5401, 0.2209]], dtype=torch.float64)

In [159]:
# Find out details about dummy tensor

print(dummy_tensor)

print(f"Datatype of tensor : {dummy_tensor.dtype}")
print(f"Shape of tensor : {dummy_tensor.shape}")
print(f"Deivce of tensor : {dummy_tensor.device}")

tensor([[0.6465, 0.4172, 0.6101, 0.6392],
        [0.8202, 0.7495, 0.5904, 0.0202],
        [0.6045, 0.7881, 0.5401, 0.2209]], dtype=torch.float64)
Datatype of tensor : torch.float64
Shape of tensor : torch.Size([3, 4])
Deivce of tensor : cpu


# Manipulating Tensors (tensor operations)

Tensor Operations include :
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [160]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [161]:
# Multply tensor by 10

tensor*10

tensor([10, 20, 30])

In [162]:
tensor

tensor([1, 2, 3])

In [163]:
# Substravt 10

tensor - 10

tensor([-9, -8, -7])

In [164]:
# Try out PyTorch in-build functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [165]:
torch.add(tensor, 10)

tensor([11, 12, 13])

# Matrix Multiplication in PyTorch

Two main ways of performing multiplication in neural networks and deep learning :
1. Element-wise multiplication
2. Matrix Multiplication

There are two main rules that performing matrix multiplication needs to satisfy :    
1. The **inner dimentions**
 *  `(3,2) @ (3,2)` won't work
 * `(2,3) @ (3,2)` will work
 * `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
 * `(2,3) @ (3,2)` -> `(2,2)`
 * `(3,2) @ (2,3)` -> `(3,3)`

In [173]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))   # this will work but not (3,2) and (3,2) due to rule 1

tensor([[0.1155, 0.4173, 0.5199],
        [0.0761, 0.1951, 0.5698],
        [0.0384, 0.1044, 0.2704]])

In [167]:
# element wise multiplication

print(tensor, "*", tensor)
print(f"Equale : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equale : tensor([1, 4, 9])


In [168]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [169]:
# matrix multiplication by hand

1*1 + 2*2 + 3*3

14

In [170]:
# understanding the time complexity between these two

%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 964 µs, sys: 0 ns, total: 964 µs
Wall time: 936 µs


In [171]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 678 µs, sys: 0 ns, total: 678 µs
Wall time: 693 µs


tensor(14)

# One of the most common errors in Deep Learning  is shape errors

In [175]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [6,7]])
tensor_B =  torch.tensor([
    [8,6,6],
    [4,5,6]
])

In [176]:
torch.matmul(tensor_A, tensor_B)

tensor([[16, 16, 18],
        [40, 38, 42],
        [76, 71, 78]])

In [177]:
# bro this is just matrix multiplication we all hav studied in class 11 or 10th already
# rule : (m*n) @ (n*m/anything) = (m*m/anything)

# Finding the min, max, mean, sum, etc (tensor aggregation)

In [190]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [191]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [192]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [193]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()  # correct dtype is required as it was int, torch.mean() requires a tensor of float32

(tensor(46.), tensor(46.))

In [194]:
x.sum(), torch.sum(x)

(tensor(460), tensor(460))

# Finding the positional min and max

In [195]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [196]:
# find the tensor that has the minimum value with argmin() -> returns the index position of target tensor where min value occurs

x.argmin()

tensor(0)

In [197]:
x[0]

tensor(1)

In [198]:
# find the tensor that has the max value with argmin() -> returns the index position of target tensor where max value occurs

x.argmax()

tensor(9)

In [199]:
x[9]

tensor(91)

# **Reshaping, stacking, squeezing and unsqueezing tensors**
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keeps the same memory as the original tensor
* Stacking -  combines multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze -  removes all `1` dimension from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensiuon permuted(swapped) in a certain way

In [200]:
# Let's create a tensor

import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [201]:
# Add an extra dimension by reshaping

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [202]:
# or

x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [203]:
# Change the view

z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [204]:
# Changing z changes x (bcz a view of a tensor shares the same memory as the original tensor)

z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [208]:
# Stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x], dim = 0)   # dim is either 0 or 1, try it by yourself to check what happens by changing dimension
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])